name: Update Lists
on:
#   schedule:
#     - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: mkdir dist && sort -u mirrors/* | gzip -9 > dist/blockp2p.list.gz
      - uses: pyTooling/Actions/releaser@r6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "nightly"
          files: |
            dist/*
